---
"$schema": http://json-schema.org/draft-04/schema#
title: Bundle Config
description: A config object for a bundle to be installed
type: object
required:
- bundle
- commands
properties:
  bundle:
    type: object
    required:
    - name
    properties:
      name:
        type: string
        description: The name of the bundle
      install:
        type: string
        description: The path to the script to install the bundle
      uninstall:
        type: string
        description: The path to the script to uninstall the bundle
  templates:
    type: array
    items:
      "$ref": "#/definitions/template"
  permissions:
    type: array
    items:
      type: string
  rules:
    type: array
    items:
      type: string
  commands:
    type: array
    items:
      "$ref": "#/definitions/command"
    minItems: 1
    uniqueItems: true
definitions:
  command:
    type: object
    required:
    - name
    - executable
    - version
    - enforcing
    properties:
      name:
        type: string
      version:
        type: string
      executable:
        type: string
      enforcing:
        type: boolean
      calling_convention:
        enum:
        - bound
        - all
      env_vars:
        type: object
      documentation:
        type: string
      options:
        type: array
        items:
          type: object
          properties:
            type:
              enum:
              - string
              - int
              - bool
            required:
              type: boolean
            name:
              type: string
  template:
    type: object
    required:
    - name
    - adapter
    - path
    properties:
      name:
        type: string
      adapter:
        enum:
        - slack
        - hipchat
      path:
        type: string

